### ISSUE TITLE
Is there a plan to launch model tutorials such as LLAMA  in the future?

### ISSUE THREAD

**Issue by dsp6414** [DunnBC22/NLP_Projects#2]
highly successful tutorials, thank you!

**Comment by DunnBC22** [comment]
Hi @dsp6414, Thank you for the compliment. As for if I am going to launch tutorials on LLaMa in the future, it is tough to say for certain. I do not plan on it right now, but I never say never.

**Comment by dsp6414** [comment]
已收到！

**Comment by dsp6414** [comment]
Thank you for your reply.～**～

**Comment by DunnBC22** [comment]
You are welcome!
